### ISSUE TITLE
#ADD Barns Finance running over polygon

### ISSUE THREAD

**Issue by BarnsFinance** [vfat-tools/vfat-tools#1438]
Farm Token - 0xfe8203070b18752702cE8E60cDC1d524E99749DE // https://polygonscan.com/address/0xfe8203070b18752702cE8E60cDC1d524E99749DE#code
Masterchef - 0xA46b3A6aaA8FC78f641E0D7C2969Ae06120764d8 //https://polygonscan.com/address/0xA46b3A6aaA8FC78f641E0D7C2969Ae06120764d8#code
Vault - 0x7885A1be4cF467b5209Da30C72454860614eac26 // https://polygonscan.com/address/0x7885A1be4cF467b5209Da30C72454860614eac26#code

Thankyou...!

**Comment by Dimosgr** [comment]
Is there any url for the site?

**Comment by BarnsFinance** [comment]
YES WE HAVE 
https://barns.finance/

**Comment by BarnsFinance** [comment]
it's not yet visible on vfat can you please check

**Comment by vfat0** [comment]
the site is not updated immediately after a merge, should be done soon though

**Comment by BarnsFinance** [comment]
okay , thanks a lot

**Comment by BarnsFinance** [comment]
hey, the link disapeared again can you please look into this

**Comment by Dimosgr** [comment]
Ok i fixed it but you have to wait until the next update.

**Comment by BarnsFinance** [comment]
hey, the link disapeared again can you please fix it ?

**Comment by Dimosgr** [comment]
ok its ready

**Comment by BarnsFinance** [comment]
is site updated ?

**Comment by Dimosgr** [comment]
Not yet. It will be during the day but I don’t know when exactly. 


Στάλθηκε από το Ταχυδρομείο Yahoo για iPhone


Στις Παρασκευή, Αυγούστου 20, 2021, 7:56 πμ, ο χρήστης BarnsFinance ***@***.***> έγραψε:




is site updated ?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
