### ISSUE TITLE
Smartcoin on AVAX showing no data

### ISSUE THREAD

**Issue by hacktek** [vfat-tools/vfat-tools#1995]
https://vfat.tools/avax/smartcoin/

I believe this is pointing to the old contract. They've migrated to smartercoin now.

https://smartcoin-tokenomics.gitbook.io/smartcoin-tokenomics/smartcoin/contracts

**Comment by Dimosgr** [comment]
Hey there. I have checked it and I'm using the same contract
![image](https://user-images.githubusercontent.com/36194185/141262458-b3fd23c7-ca32-4689-bba6-463c4e031244.png)

The problem is that the contract is not verified and I can't see the code to find out what is going wrong.
![image](https://user-images.githubusercontent.com/36194185/141262683-0bd61e08-d282-4424-8480-a5d44c9a8f79.png)

**Comment by Dimosgr** [comment]
found the new contract address and updated
![image](https://user-images.githubusercontent.com/36194185/142757630-a607e249-fd42-45d5-811b-50d2c0c9ee7c.png)
