### ISSUE TITLE
multiple issues per Discord

### ISSUE THREAD

**Issue by awbvious** [vfat-tools/vfat-tools#2256]
a) snowball on avalanche is not working b) why is beefy not on all its supported chains (e.g. Avax)? c) ever considered impermax (any chain)? d) why is "All" https://vfat.tools/all/ only Ethereum--shouldn't "All" list everything on all the chain pages and a new page called "Ethereum" be created for Ethereum? 

Note, I asked these questions in Discord and was told by a Community mod 'acidbird':

acidbird
 — 
Yesterday at 10:31 PM
please use https://github.com/vfat-tools/vfat-tools for these, you can make separate issues

I then told "acidbird" that I was fine with just mentioning this on Discord, but I can put them on github if a Dev wants me to put one or any of these on github,

acidbird
 — 
Today at 8:40 PM
You can start with 1 issue or make 1 issue for all at once. 

Thus, here we are.

**Comment by Dimosgr** [comment]
Hi, Im pretty sure that he told that because it is a big request and by added it here it cant be missed. I have added beefy on avax and the new vaults for snowball. Nevertheless, for impermax I tried to add it but there is a different masterchef and they don't provide the staking tokens. Finally, I am not responsible for the D request.

**Comment by Dimosgr** [comment]
Closed because of inactivation.
